debug: true
server:
  port: 8888
  tomcat:
    uri-encoding: UTF-8
spring:
  jackson:
    date-format: "yyyy-MM-dd HH:mm:ss"
    property-naming-strategy: CAMEL_CASE_TO_LOWER_CASE_WITH_UNDERSCORES
  thymeleaf:
    cache: false
logging:
  level:
    org.springframework.web: INFO
    me.iszhenyu: DEBUG
    root: INFO
jwt:
  key: mykey
  token-header-name: X-AUTH-TOKEN
  token-cookie-name: AUTH-TOKEN
  token-expire-day: 30