debug: true
server:
  port: 8888
  tomcat:
    uri-encoding: UTF-8
spring:
  thymeleaf:
    cache: false
  profiles:
    active: dev
jwt:
  key: mykey
  token-header-name: X-AUTH-TOKEN
  token-cookie-name: AUTH-TOKEN
  token-expire-day: 30
