debug: true
server:
  port: 8888
  tomcat:
    uri-encoding: UTF-8
spring:
  jackson:
    date-format: "yyyy-MM-dd HH:mm:ss"
    property-naming-strategy: CAMEL_CASE_TO_LOWER_CASE_WITH_UNDERSCORES
    default-property-inclusion: non_null
  thymeleaf:
    cache: false
  profiles:
    active: dev
jwt:
  key: mykey
  token-header-name: X-AUTH-TOKEN
  token-cookie-name: AUTH-TOKEN
  token-expire-day: 30
logging:
  config: classpath:logback/logback-spring.xml