spring:
  jackson:
    date-format: "yyyy-MM-dd HH:mm:ss"
    property-naming-strategy: CAMEL_CASE_TO_LOWER_CASE_WITH_UNDERSCORES
    default-property-inclusion: non_null
  datasource:
    name: ifiji
    url: jdbc:mysql://127.0.0.1:3306/base_on_springboot
    username: root
    password: 3013689
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    database: 0
    pool:
      max-wait: -1
      max-idle: 8
      min-idle: 0
      max-active: 8
    timeout: 0
#  cache:
#    ehcache:
#      config: classpath:config/ehcache-fiji.xml
#    type: redis
mybatis:
  type-aliases-package: me.iszhenyu.ifiji.model
  type-handlers-package: me.iszhenyu.ifiji.core.dao.typehandler
  mapper-locations: classpath:mapper/*.xml
  configuration:
    default-fetch-size: 100
    default-statement-timeout: 30
    map-underscore-to-camel-case: true